import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

import UploadImage from './components/UploadImage';
import InputText from './components/InputText';

export default function Home() {
  const [dialog, setDialog] = useState({
    image: false,
    text: false,
    background: false
  });

  const handleDialog = (dialogName) => {
    setDialog((prevState) => ({
      ...prevState,
      [dialogName]: true
    }));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>測驗封面</header>
      <main className={styles.container}>
        <section className={styles.section}>
          <button type="button" onClick={() => handleDialog('image')}>
            上傳測驗 Logo
          </button>
        </section>
        <section className={styles.section}>
          <button type="button" onClick={() => handleDialog('image')}>
            上傳測驗視覺
          </button>
        </section>
        <section className={styles.section}>
          <button type="button" onClick={() => handleDialog('text')}>
            輸入測驗名稱
          </button>
        </section>
        <section className={styles.section}>
          <button type="button" onClick={() => handleDialog('background')}>
            背景設定
          </button>
        </section>
      </main>
      <UploadImage isOpen={dialog.image} />
      <InputText isOpen={dialog.text} />
    </>
  );
}
