import Head from 'next/head';
import { useState, useReducer } from 'react';
import styles from '../styles/Home.module.css';

import Dialog from '../components/Dialog';

export default function Home() {
  const dialogReducer = (state, action) => {
    switch (action.type) {
      case 'OPEN_DIALOG':
        return {
          ...state,
          isOpen: true,
          title: action.payload.title,
          description: action.payload.description,
          inputs: action.payload.inputs
        };

      case 'CLOSE_DIALOG':
        return {
          ...state,
          isOpen: false,
          title: '',
          inputs: []
        };

      default:
        return state;
    }
  };

  const [dialogState, dispatchDialog] = useReducer(dialogReducer, {
    isOpen: false,
    title: '',
    description: '',
    inputs: []
  });

  const handleOpenDialog = (dialogTitle, dialogDescription, inputs) => {
    dispatchDialog({
      type: 'OPEN_DIALOG',
      payload: {
        title: dialogTitle,
        description: dialogDescription,
        inputs: inputs
      }
    });
  };

  const [preview, setPreview] = useState({
    logo: '',
    cover: '',
    quizName: '',
    fill: ''
  });

  // const previewReducer = (state, action) => {
  //   switch (action.type) {
  //     case 'logo':
  //       return {
  //         ...state,
  //         logo: action.payload.logo
  //       };

  //     case 'cover':
  //       return {
  //         ...state,
  //         cover: action.payload.cover
  //       };

  //     case 'quizName':
  //       return {
  //         ...state,
  //         quizName: action.payload.quizName
  //       };

  //     case 'fill':
  //       return {
  //         ...state,
  //         fill: action.payload.fill
  //       };

  //     default:
  //       return state;
  //   }
  // };

  // const [previewState, dispatchPreview] = useReducer(previewReducer, {
  //   logo: '',
  //   cover: '',
  //   quizName: '',
  //   fill: ''
  // });

  const Sections = () => {
    const sections = [
      {
        button: 'Upload Logo',
        dialogTitle: 'Logo',
        description: 'At least 360px in width with 2:1 ratio.',
        inputs: [
          {
            type: 'file',
            name: 'logo',
            accept: 'image/*'
          }
        ]
      },
      {
        button: 'Upload Cover Photo',
        dialogTitle: 'Cover Photo',
        inputs: [
          {
            type: 'file',
            name: 'cover',
            accept: 'image/*'
          }
        ]
      },
      {
        button: 'Input Quiz Name',
        dialogTitle: 'Text Input',
        inputs: [
          {
            type: 'text',
            name: 'quizName'
          }
        ]
      },
      {
        button: 'Background',
        dialogTitle: 'Background Color/Image',
        description: 'At least 360px in width with 2:1 ratio.',
        inputs: [
          {
            type: 'color',
            name: 'fill'
          }
        ]
      }
    ];

    return (
      <>
        {sections.map(({ button, dialogTitle, description, inputs }, index) => {
          return (
            <section className={styles.section} key={index}>
              {inputs.map(({ name }) => {
                return (
                  <button
                    className={`${styles.dialogButton} ${
                      name === 'quizName' && styles.dialogButtonQuizName
                    } ${!preview['quizName'] && styles.unfilled}`}
                    type="button"
                    onClick={() =>
                      handleOpenDialog(dialogTitle, description, inputs)
                    }
                    key={index}
                  >
                    {preview[name] ? preview[name] : button}
                  </button>
                );
              })}
            </section>
          );
        })}
      </>
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Cover Photo</header>
      <main className={styles.container}>
        <Sections />
      </main>
      <Dialog
        isOpen={dialogState.isOpen}
        dispatchDialog={dispatchDialog}
        dialogTitle={dialogState.title}
        dialogDescription={dialogState.description}
        inputs={dialogState.inputs}
        // dispatchPreview={dispatchPreview}
        setPreview={setPreview}
      />
    </>
  );
}
